### ISSUE TITLE
Test failure with python 3.13

### ISSUE THREAD

**Issue by xdbob** [vpelletier/python-libusb1#103]
Unit tests are failing with python 3.13 (found on fedora rawhide):

```
======================================================================
FAIL: testDefaultEnumScope (usb1.testUSB1.USBTransferTests.testDefaultEnumScope)
Enum instances must only affect the scope they are created in.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/xx/pkg/usb1/testUSB1.py", line 289, in testDefaultEnumScope
    self.assertEqual(local_dict.get(ENUM_NAME), ENUM_VALUE)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: None != 42

----------------------------------------------------------------------
Ran 13 tests in 0.079s
```

My understanding of the situation is that the test is not compatible with the new [PEP 667](https://peps.python.org/pep-0667/), specifically the following change:

> For function scopes it will return an instantaneous snapshot of the underlying frame.f_locals.

eg: we do the variable assignment **after** we took a snapshot of the locals.

Downstream fedora bug report: https://bugzilla.redhat.com/show_bug.cgi?id=2280555

**Comment by sorenstoutner** [comment]
Downstream Debian bug report:  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1090277

**Comment by vpelletier** [comment]
> the test is not compatible with the new [PEP 667](https://peps.python.org/pep-0667/)

Indeed.
