### ISSUE TITLE
Debian/Ubuntu package

### ISSUE THREAD

**Issue by diamondman** [vpelletier/python-libusb1#17]
I am a big fan of your work on this library, and believe the interface you present should be the standard way usb is interacted with in python. Unfortunately I can not rely on it when I am making debian/ubuntu packages because pip integration has always been problematic. 

I would like to request a python-usb1 and python3-usb1 packages (or whatever you want to call them) be maintained in the debian package repository. I am aware that this process is a lot more complicated than publishing a project onto pypi, but I think it will be worth it to get people access to this great library. 

I am willing to help get the packaging process started. I have never tried to get a package approved by the debian team for inclusion in the core repositories, but I have just built a package for a small python project I built, so I should be able to help at least getting it in a PPA or a private server.

**Comment by vpelletier** [comment]
Hello.
Thanks for your support ! Actually, I know (at least) two DDs, both experienced in packaging python packages, so I'll propose them to package python-libusb1 (and will propose them to name it like that modulo interpreter version, but I don't know if there is a naming convention for the right-hand side of that name).

**Comment by diamondman** [comment]
Thanks, that sounds perfect. I frankly do not care what it is called, though as you point out it should be python-* and python3-*, I would just like access to this library outside of the context of pip. I appreciate it.

**Comment by vpelletier** [comment]
I filled a [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=834369](WNPP bug requesting for packaging).

**Comment by vpelletier** [comment]
python-libusb1 is now in sid (in 3 packages: python-, python3- and pypy-), and should migrate to testing before the upcoming freeze. Yay !
