### ISSUE TITLE
LIBUSB_ERROR_TIMEOUT [-7] during "getManufacturer()"

### ISSUE THREAD

**Issue by dwu-zingbox** [vpelletier/python-libusb1#2]
Running on ubuntu 14.10 x64. getManufacturer() returned with error. Trace the error back as LIBUSB_ERROR_TIMEOUT [-7].

-Dennis

**Comment by vpelletier** [comment]
Could you check the content of `/sys/bus/usb/devices/$BUS-$PORT/manufacturer` file corresponding to your device ?
You can know `$BUS` and `$PORT` with `lsusb -t` .

**Comment by dwu-zingbox** [comment]
lsusb shows it on bus 2 dev 8 but sysfs put it under 2-2:2 folder. This Texas Instrument device, 0451:16ae, is installed on a USB hub. Maybe this is where the problem come from.

dennis@ubuntu:/sys/bus/usb/devices$ lsusb -t
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=uhci_hcd/2p, 12M
    |__ Port 1: Dev 2, If 0, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 2: Dev 3, If 0, Class=Hub, Driver=hub/7p, 12M
        |__ Port 1: Dev 4, If 0, Class=Wireless, Driver=btusb, 12M
        |__ Port 1: Dev 4, If 1, Class=Wireless, Driver=btusb, 12M
        |__ Port 2: Dev 8, If 0, Class=Vendor Specific Class, Driver=, 12M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=ehci-pci/6p, 480M

dennis@ubuntu:/sys/bus/usb/devices$ lsusb -v -s 2:8

Bus 002 Device 008: ID 0451:16ae Texas Instruments, Inc. 
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        32
  idVendor           0x0451 Texas Instruments, Inc.
  idProduct          0x16ae 
  bcdDevice           12.53
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           25
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass    255 Vendor Specific Subclass
      bInterfaceProtocol    255 Vendor Specific Protocol
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               5

dennis@ubuntu:/sys/bus/usb/devices$ ls 2-2.2
2-2.2:1.0            bmAttributes        dev          manufacturer  speed
authorized           bMaxPacketSize0     devnum       maxchild      subsystem
avoid_reset_quirk    bMaxPower           devpath      port          uevent
bcdDevice            bNumConfigurations  driver       power         urbnum
bConfigurationValue  bNumInterfaces      ep_00        product       version
bDeviceClass         busnum              idProduct    quirks
bDeviceProtocol      configuration       idVendor     removable
bDeviceSubClass      descriptors         ltm_capable  remove

dennis@ubuntu:/sys/bus/usb/devices$ cat 2-2.2/manufacturer 
Texas Instruments
dennis@ubuntu:/sys/bus/usb/devices$

**Comment by vpelletier** [comment]
> lsusb shows it on bus 2 dev 8 but sysfs put it under 2-2:2 folder

This puzzled me a bit when I checked this too, but what sysfs represents is that the device is plugged in port n°2 of second USB bus - which is independent from the dynamically assigned USB address which happens to be 8 here (which depends on enumeration order and plug/unplug history).

> $ lsusb -v -s 2:8
[...]
> iManufacturer 1
[...]
> $ cat 2-2.2/manufacturer 
> Texas Instruments

Aha, so the string descriptor is actually present and could be retrieved by the kernel when enumerating the device. But for some reason, when libusb tried later to read string descriptor 1 (as retrieved from USB descriptor field iManufacturer), something timed out.

It may be a bug in device's firmware, or that python-libusb should not call libusb_get_string_descriptor_ascii for this.

By the way, could you paste the python-libusb error traceback ? python-libusb does not use kernel's cached string but actually tries to issue a USB request, for which it has to be able to open the device temporarily. Maybe the failure is not in trying to read the string descriptor, but actually when trying to open the device.

**Comment by dwu-zingbox** [comment]
Traced the error back to getASCIIStringDescriptor() when calling libusb1.libusb_get_string_descriptor_ascii(), returned as -7.

--- Added code to display error

    def getASCIIStringDescriptor(self, descriptor):
        """
        Fetch description string for given descriptor in first available
        language.
        Return value is an ASCII string.
        Return None if there is no such descriptor on device.
        """
        descriptor_string = create_binary_buffer(STRING_LENGTH)
        result = libusb1.libusb_get_string_descriptor_ascii(self.__handle,
             descriptor, descriptor_string, sizeof(descriptor_string))
        if result == libusb1.LIBUSB_ERROR_NOT_FOUND:
            return None
        if result < 0:
            print('getASCIIStringDescriptor(): failed libusb_get_string_descriptor_ascii(), result=%i' % result)          <----Added line
            raise libusb1.USBError(result)
        return descriptor_string.value.decode('ASCII')

--- Screen dump
getASCIIStringDescriptor(): failed libusb_get_string_descriptor_ascii(), result=-7

More info: prior call for getBusNumber() and getDeviceAddress() returned normally so the device was actually found. The higher level code calling usb1 module are,

def get_CC2531():
    cc2531 = []
    ctx = usb1.USBContext()
    #
    for dev in ctx.getDeviceList(skip_on_error=True):
        if dev.getVendorID() == VID and dev.getProductID() == PID:
            LOG(' found CC2531 @ USB bus %i and address %i' \
                % (dev.getBusNumber(), dev.getDeviceAddress()))
            cc2531.append(dev)
    #
    if cc2531 == []:
        LOG(' no CC2531 found (VID %x PID %x)' % (VID, PID))
        return []
    #
    try:
        manuf = cc2531[0].getManufacturer()
    except libusb1.USBError:
	#LOG(libusb1.USBError)
        LOG(' cannot open USB device through libusb:' \
            ' add yourself in the "root" group or make an udev rule')
        return []
    # 
    return cc2531

Maybe the problem is with libusb1

**Comment by vpelletier** [comment]
> More info: prior call for getBusNumber() and getDeviceAddress() returned normally so the device was actually found.

Actually, if the device wasn't present at all, you shouldn't get a USBDevice instance. getManufacturer, getProduct and getSerialNumber are special as they need to open the device temporarily. I think the other libusb functions just read data from kernel's copy of device's descriptor, making them guaranteed to succeed. But as you demonstrated, opening is not the issue (...or at least no issue is detected at open level).

You can emulate libusb_get_string_descriptor_ascii call with (quick & dirty):
```python
import usb1, libusb1
print usb1.USBContext().openByVendorIDAndProductID(
  VID,
  PID,
  skip_on_access_error=True,
).controlRead(
  libusb1.LIBUSB_TYPE_STANDARD,
  libusb1.LIBUSB_REQUEST_GET_DESCRIPTOR,
  (libusb1.LIBUSB_DT_STRING << 8) | 1, # 1 being iManufacturer
  0, # Default language
  255, # How many bytes to read
)[2:].decode('utf16') # Skip 2 bytes: descriptor length and type.
```
If this works, try calling getManufacturer instead (replacing `openByVendorIDAndProductID` with `getByVendorIDAndProductID`), and gradually getting closer to the original code.

> Maybe the problem is with libusb1

At least, python-libusb1 will not generate such error on its own, so something wrong happens somewhere else. But its ultimate cause can be some libusb misuse on my (python-libusb1) part.

I can think of two more lower-level debugging methods:
- [usbmon](https://www.kernel.org/doc/Documentation/usb/usbmon.txt) or via wireshark to get the full dump of exchanges with the device. This would show if the device is misbehaving (ex, a GET_DESCRIPTOR urb going down with no response/stall/...). [USB in a nutshell](http://www.beyondlogic.org/usbnutshell/usb6.shtml#StandardDeviceRequests) part on standard device requests can help understanding what is going on. If you sniff when plugging the device, you should see working GET_DESCRIPTOR requests for these string descriptor, which should help compare.
- executing python under strace, so as to find failing syscall if a libusb bug is suspected (ie, if usbmon yields nothing surprising)

I feel like I'm missing something, sorry for not providing more specific guidance. As a last resort, writing a quick & dirty C equivalent should be relatively easy, and then you can report the issue (...if C code also exhibits it) on [libusb's mailing list](http://www.libusb.org/wiki/MailingList).

**Comment by dwu-zingbox** [comment]
Vincent,

Thanks being patient with my problem. It will take me some time to verify all your ideas. And I'm switched to other higher priority stuff. So please expect idle me for a couple of days. Appreciate you help again.

-D

**Comment by dwu-zingbox** [comment]
Did a simple C program calling libusb1 and found control_transfer sometime returned with timeout error but actually the transaction is done successfully. It only happens during write not never happen during read. So it is not a python-libusb1 problem but I'd suggest some tweak to go around this issue like ignoring timeout error for now.

**Comment by vpelletier** [comment]
Thanks a lot for your tests.
I'm not sure I should ignore errors (even just timeout ones) at python-libusb1 level, though, as this may be a firmware bug specific to this device type.
Did you check (via usbmon or pcap/wireshark) how the device behaves from kernel's point of view ? Owning a physical usb analyser, I cannot tell exactly which behaviour would be visible wit these tools. For example, a device is supposed to respond quickly that it is still busy processing a request - with a NAK or NYET handshake (from a quick look at the cc2531 datasheet, it is a full-speed only device, so NAK only) - but usbmon will probably only report final completion without all intermediate handshakes.
Actually, the situation may be even more complex from USB protocol point of view, as I now recall you said the device is plugged on a hub - and if this is a high-speed hub, it will have some encapsulation protocol to wrap full-speed packets... Do the timeouts also occur without this hub and/or with another hub ?

**Comment by vpelletier** [comment]
Closing as this is now inactive, and likely not a python-libusb1 issue.
