### ISSUE TITLE
Can't install libusb with recent versions of setuptools

### ISSUE THREAD

**Issue by kavehv** [vpelletier/python-libusb1#23]
> $ sudo -H pip3 install libusb1
> Collecting libusb1
>   Using cached libusb1-1.6.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/tmp/pip-build-o4hqf9gk/libusb1/setup.py", line 16, in <module>
>         from setuptools import setup
>     ImportError: cannot import name 'setup'
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-o4hqf9gk/libusb1/

I had to downgrade to setuptools version 20.10.1 to successfully install.

**Comment by vpelletier** [comment]
What is the version of setuptools you have issues with ?

FWIW, I have 28.7.1 (debian package 28.7.1-1, current on sid) and it works. It would be surprising for setuptools to stop exposing "setup".

Would the same issue also happen with other python packages ?

**Comment by kavehv** [comment]
I was using the pip3 package on macOS.


From: Vincent Pelletier <notifications@github.com>
<notifications@github.com>
Reply: vpelletier/python-libusb1
<reply@reply.github.com>
<reply@reply.github.com>
Date: December 9, 2016 at 11:39:37 PM
To: vpelletier/python-libusb1 <python-libusb1@noreply.github.com>
<python-libusb1@noreply.github.com>
CC: Kaveh <kaveh@vaghefi.org> <kaveh@vaghefi.org>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [vpelletier/python-libusb1] Can't install libusb with recent
versions of setuptools (#23)

What is the version of setuptools you have issues with ?

**Comment by mcuee** [comment]
This is probably an old issue which no longer applies. I have never have any issue with python-libusb1 under macOS using Homebrew.

**Comment by vpelletier** [comment]
Thanks for the report. Closing this.
