### ISSUE TITLE
AttributeError: 'int' object has no attribute 'value' in function iterISO

### ISSUE THREAD

**Issue by LemarinelNet** [vpelletier/python-libusb1#24]
I have a problem while trying to make an ISOCHRONOUS transfert.
I have two computers (work and home), and it did worked at work.
I've just reinstalled my home computer with ubuntu 16.04, and python-libusb1 is installed from last source.

I've got the following error, which refers to this part of code : 
AttributeError: 'int' object has no attribute 'value'

Code : (line 694 of usb.py ) : 
`
        buffer_position = transfer.buffer.value
`
I can't figure out what I've done bad ! ;)

Thanks for you help !

**Comment by vpelletier** [comment]
Indeed, this is a regression in 1.6, thanks for the report and sorry for the regression.

Could you test latest master ? It should be fixed there, and I added a test (which did reproduce the exception).

**Comment by LemarinelNet** [comment]
Hi ! 
Fast fix :) 
I did tried with my work PC before updating : I was in 1.5.2.
I did upgrade from master, and the error is gone. 
But, I don't have any data while transfering from my USB device (got series of zeros....)
I'll have to test one more time back with 1.5.2...

**Comment by vpelletier** [comment]
Thanks for testing and reporting, I just released 1.6.1 on pypi.
