### ISSUE TITLE
USBErrorBusy with devices in hot-plug events notifications

### ISSUE THREAD

**Issue by lifely** [vpelletier/python-libusb1#29]
Hello guys,

I've been playing and implementing some backend with `usb1` and `libusb1` for the past week,
trying to use the event to detect some devices and manage them once registered.

I've stumbled across a weird behaviour for me and would like to know if this is supposed to be a bug (in libusb or python-usb1) or this is expected behaviour that i'm supposed to handle.

The issues appears during hot plug events, when a device is plug-in while listening, trying to get the `device.getSerialNumber()` raise `USBErrorBusy`.

I've tried a multiple of solution including `detachKernelDriver`, `claimInterface`, `releaseInterface` and `resetDevice` but nothing seems to affect the issue.

Strangely if the devices are already plugging in before registering for hot-plugs event, the serialNumber can be retrieve and no `USBErrorBusy` is raised.

I've found an ugly work-around which is to fetch the device and serialNumber through a second `USBContext` instance instanciated on the fly, which make me feel like it's a bug somewhere.

I'm joining this issue with an sample script that reproduce the issue, you can easily test it with plugin a android phone in and out, and also having the phone already plug-in before launching the script.

Here the Work-around in details and next is a sample text output:
```python
try:
    print "Device SerialNumber: %s" % device.getSerialNumber()
except Exception as e:
    with usb1.USBContext() as context:
        device_ = context.getByVendorIDAndProductID(device.getVendorID(), device.getProductID())
        serialNumber_ = device_.getSerialNumber()
        print "Fetching device with new usbContext fix usb_busy error: %s" % serialNumber_
```

```
Registering hotplug callback...
Device arrived: Bus 020 Device 024: ID 18d1:4ee2 - 1
Device SerialNumber: ENU7N15B14005190
Device arrived: Bus 026 Device 003: ID 05ac:8510 - 1
Device SerialNumber: CC2D820AKCDN9KB0
Device arrived: Bus 029 Device 007: ID 05ac:8286 - 1
Device SerialNumber: None
Device arrived: Bus 029 Device 004: ID 05ac:0262 - 1
Device SerialNumber: None
Device arrived: Bus 029 Device 003: ID 0a5c:4500 - 1
Device SerialNumber: None
Device arrived: Bus 029 Device 002: ID 0424:2512 - 1
Device SerialNumber: None
Device arrived: Bus 026 Device 001: ID 8087:0024 - 1
Device SerialNumber: None
Device arrived: Bus 029 Device 001: ID 8087:0024 - 1
Device SerialNumber: None
Callback registered. Monitoring events, ^C to exit

Device left: Bus 020 Device 024: ID 18d1:4ee2 - 1

Device arrived: Bus 020 Device 025: ID 18d1:4ee2 - 1
device.getSerialNumber failed with: LIBUSB_ERROR_BUSY [-6] (USBErrorBusy)
Fetching device with new usbContext fix usb_busy error: ENU7N15B14005190

Device left: Bus 020 Device 025: ID 18d1:4ee2 - 1

Device arrived: Bus 020 Device 023: ID 18d1:4ee2 - 1
device.getSerialNumber failed with: LIBUSB_ERROR_BUSY [-6] (USBErrorBusy)
Fetching device with new usbContext fix usb_busy error: ENU7N15B14005190
```

Could i fix the issue in the first place without needing my work-around ?
Should this be reported to `libusb1` or handle directly in `python-usb1` ?

Is there any device release business logic that should happen during hot-plug disconnect or connect event to make the usb "un-busy"

Thanks for the help guys. 

`hotplug.py`
```python
#!/usr/bin/env python
# Copyright (C) 2013-2016  Vincent Pelletier <plr.vincent@gmail.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
import usb1

eventType = {   usb1.HOTPLUG_EVENT_DEVICE_ARRIVED: 'arrived',
                usb1.HOTPLUG_EVENT_DEVICE_LEFT: 'left', }

def hotplug_callback(context, device, event):
    print "Device %s: %s - %s" % (eventType[event], device, device.getNumConfigurations())

    try:
        print "Device SerialNumber: %s" % device.getSerialNumber()
    except Exception as e:
        if type(e) is usb1.USBErrorNoDevice:
            return 

        print "device.getSerialNumber failed with: %s (%s)" % (e, type(e).__name__)        
        with usb1.USBContext() as context:
            device_ = context.getByVendorIDAndProductID(device.getVendorID(), device.getProductID())
            serialNumber_ = device_.getSerialNumber()
            print "Fetching device with new usbContext fix usb_busy error: %s" % serialNumber_
    pass

def main():
    with usb1.USBContext() as context:
        if not context.hasCapability(usb1.CAP_HAS_HOTPLUG):
            print 'Hotplug support is missing. Please update your libusb version.'
            return
        print 'Registering hotplug callback...'
        opaque = context.hotplugRegisterCallback(hotplug_callback)
        print 'Callback registered. Monitoring events, ^C to exit'
        try:
            while True:
                context.handleEvents()
        except (KeyboardInterrupt, SystemExit):
            print 'Exiting'

if __name__ == '__main__':
    main()
```

**Comment by vpelletier** [comment]
Hello,

Thanks for the detailed report.

> The issues appears during hot plug events, when a device is plug-in while listening, trying to get the device.getSerialNumber() raise USBErrorBusy.

`getSerialNumber` is special in that it opens the device and issues a synchronous "setup" request to the device to get the string descriptor containing the serial number. And synchronous calls are just asynchronous calls plus blocking event handling called internally.

Grepping a bit in libusb-1.0 code, I stumbled on [this](https://github.com/libusb/libusb/blob/b99391deb4894bbfff59fab985c99fc55a43169a/libusb/sync.c#L89). This is not visible in the [on-line documentation](http://libusb.sourceforge.net/api-1.0/group__syncio.html#gadb11f7a761bd12fc77a07f4568d56f38), so I guess it was not re-generated from source for a while (it dates from a commit from late 2015). @dickens : could you refresh the docs ?

This would likely explain why creating a separate context helps: I believe each context uses/needs its own event handling, so another context will not "see" the original one is still doing event handling.

This means that another fix could be to append the device received during hotplug event and only use it outside of event handling call stack (move even handling to a thread and use some IPC to notify the even happened available, or process the list when `handleEvents` returns...).

**Comment by lifely** [comment]
Thanks,

That's a great answer too, i've actually though of that possibility before but that was the only thing i didn't test. (like always :/)

It make sense, to mark a device `BUSY` during the event handling callback and context. It also mean my solution will not suffer too much from this issue, i'm only needing the `serial number` during the event callback, the stack will then use the device store somewhere during such context event.

I think i'll stick to my solution for now in the event context, and use the normal device later-on.
I've edited my sample script to include an example of this behaviour using `Threading.Timer`

Calling a function on a timer during the event context/callback, the function will then be call outside the event context and prevent `USBErrorBusy` errors
`threading.Timer(15, outside_event_context, [device]).start()`

```
Registering hotplug callback...
Device arrived: Bus 020 Device 006: ID 18d1:4ee2 - 1
Device SerialNumber: ENU7N15B14005190
Device arrived: Bus 026 Device 003: ID 05ac:8510 - 1
Device SerialNumber: CC2D820AKCDN9KB0
Device arrived: Bus 029 Device 005: ID 05ac:8286 - 1
Device SerialNumber: None
Device arrived: Bus 029 Device 004: ID 0a5c:4500 - 1
Device SerialNumber: None
Device arrived: Bus 029 Device 003: ID 05ac:0262 - 1
Device SerialNumber: None
Device arrived: Bus 029 Device 002: ID 0424:2512 - 1
Device SerialNumber: None
Device arrived: Bus 029 Device 001: ID 8087:0024 - 1
Device SerialNumber: None
Device arrived: Bus 026 Device 001: ID 8087:0024 - 1
Device SerialNumber: None
Callback registered. Monitoring events, ^C to exit

Device SerialNumber: None (outside context)
Device SerialNumber: None (outside context)
Device SerialNumber: None (outside context)
Device SerialNumber: CC2D820AKCDN9KB0 (outside context)
Device SerialNumber: None (outside context)
Device SerialNumber: ENU7N15B14005190 (outside context)
Device SerialNumber: None (outside context)Device SerialNumber: None (outside context)

Device left: Bus 020 Device 006: ID 18d1:4ee2 - 1

Device arrived: Bus 020 Device 007: ID 18d1:4ee2 - 1
device.getSerialNumber failed with: LIBUSB_ERROR_BUSY [-6] (USBErrorBusy)
Fetching device with new usbContext fix usb_busy error: ENU7N15B14005190

Device SerialNumber: ENU7N15B14005190 (outside context)
```


see 
`hotplug.py`
```python
#!/usr/bin/env python
# Copyright (C) 2013-2016  Vincent Pelletier <plr.vincent@gmail.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
import usb1, threading

eventType = {   usb1.HOTPLUG_EVENT_DEVICE_ARRIVED: 'arrived',
                usb1.HOTPLUG_EVENT_DEVICE_LEFT: 'left', }

def outside_event_context(device):
    try:
        print "Device SerialNumber: %s (outside context)" % device.getSerialNumber()
    except Exception as e:
        if type(e) is usb1.USBErrorNoDevice:
            return 

        print "device.getSerialNumber failed with: %s (%s) (outside context)" % (e, type(e).__name__)        
        with usb1.USBContext() as context:
            device_ = context.getByVendorIDAndProductID(device.getVendorID(), device.getProductID())
            serialNumber_ = device_.getSerialNumber()
            print "Fetching device with new usbContext fix usb_busy error: %s (outside context)" % serialNumber_

def hotplug_callback(context, device, event):
    print "Device %s: %s - %s" % (eventType[event], device, device.getNumConfigurations())

    try:
        print "Device SerialNumber: %s" % device.getSerialNumber()
    except Exception as e:
        if type(e) is usb1.USBErrorNoDevice:
            return 

        print "device.getSerialNumber failed with: %s (%s)" % (e, type(e).__name__)        
        with usb1.USBContext() as context:
            device_ = context.getByVendorIDAndProductID(device.getVendorID(), device.getProductID())
            serialNumber_ = device_.getSerialNumber()
            print "Fetching device with new usbContext fix usb_busy error: %s" % serialNumber_

    threading.Timer(15, outside_event_context, [device]).start()
    pass

def main():
    with usb1.USBContext() as context:
        if not context.hasCapability(usb1.CAP_HAS_HOTPLUG):
            print 'Hotplug support is missing. Please update your libusb version.'
            return
        print 'Registering hotplug callback...'
        opaque = context.hotplugRegisterCallback(hotplug_callback)
        print 'Callback registered. Monitoring events, ^C to exit'
        try:
            while True:
                context.handleEvents()
        except (KeyboardInterrupt, SystemExit):
            print 'Exiting'

if __name__ == '__main__':
    main()
```

I think this issue should/could be marked as solved, maybe with referencing the context locking behaviour in some documentation out there, like in the `hotplug.py` on the repo for example.

Thanks !

**Comment by vpelletier** [comment]
> maybe with referencing the context locking behaviour in some documentation out there, like in the `hotplug.py` on the repo for example.

I agree. I added a mention on `usb1.USBContext.hotplugRegisterCallback` docstring, plus documented more explicitly the few methods on USBDevice which issue synchronous calls, plus comments in both hotplug examples: 896d600d0daedbd7cd48d187da59ee8158a5713f .

I guess the same limitation also applies during "normal" (non-hotplug) even handling, ie async API callbacks, but issuing a synchronous call inside async handler is less likely to happen and more likely to be quickly identified as problematic, so I think I do not need to document this limitation.
