### ISSUE TITLE
USBContext waitForEvent may not work correctly.

### ISSUE THREAD

**Issue by rpcope1** [vpelletier/python-libusb1#3]
Hey, I am trying to use the USBPollerThread class, and my Python script seems to fall apart on the waitForEvent() method in USBContext, which is:

    @_validContext
    def waitForEvent(self):
        """
        See libusb_wait_for_event doc.
        """
        libusb1.libusb_wait_for_event(self.__context_p)

However the wrapper for libusb_wait_for_event() is:
       
      #int libusb_wait_for_event(libusb_context *ctx, struct timeval *tv);
      libusb_wait_for_event = libusb.libusb_wait_for_event
      libusb_wait_for_event.argtypes = [libusb_context_p, timeval_p]

It looks like the context waitForEvent call is missing a timeval argument. Any ideas here? Maybe I'm missing something...

**Comment by vpelletier** [comment]
Pull-request #4 merged, and 1.3.1 released (tagged & egg uploaded to pypi).

**Comment by vpelletier** [comment]
BTW, I also use python-libusb1 to drive a device with the FX2-LP: [ITI1480A-linux](/vpelletier/ITI1480A-linux), see [iti1480a/capture.py](/vpelletier/ITI1480A-linux/blob/master/iti1480a/capture.py). I didn't specially fine-tune the number of pending transfers nor the buffer size, the rest should be easy to reuse (or at least get ideas from).
