### ISSUE TITLE
Occasional segfault if `USBTransfer.close` is called in callback

### ISSUE THREAD

**Issue by forrestv** [vpelletier/python-libusb1#47]
During the entirety of the time that libusb is calling the callback that python-libusb1 provides, the thunk (stored in `USBTransfer.__ctypesCallbackWrapper`) needs to be kept alive. Calling `USBTransfer.close` within the callback destroys the (still-running) thunk, causing occasional segfaults in libffi when returning back to libusb.

Currently, the `__submitted` flag and `before_submit`/`after_completion` callbacks are used to keep the `USBTransfer` alive, and that's almost sufficient. The `__ctypesCallbackWrapper` is special, though; it needs to be guaranteed to live a *little* bit longer - until after `__callbackWrapper` has returned.

I think that the easiest fix here is to:
1. Make `__callbackWrapper` a `@staticmethod`
2. Create `__ctypesCallbackWrapper` in the class body rather than in `__init__` so it's shared between all `USBTransfer`s
3. Use a dict of currently submitted transfers to get the `USBTransfer` object corresponding to the libusb transfer pointer that is provided to the callback

**Comment by vpelletier** [comment]
Thanks for this excellent report. The investigation must have been painful, I am very sorry about this.

I pushed a tentative fix to the new (and temporary) [keep_callback_alive](/vpelletier/python-libusb1/commits/keep_callback_alive) branch. Would you mind giving it a try, and reporting whether it fixes this issue ?

This patch is not as clean as I would like it to be, I may be missing something.

**Comment by forrestv** [comment]
My code that previously segfaulted after about 12 on average has been running for a few days without problems. I think that that's good evidence that the problem is fixed.

**Comment by vpelletier** [comment]
> When I ran it with the branch at first, I got this error:

Good catch, and the comment above that line is also a mistake (which shows that I initially did consider `None` and then forgot about it): that line was originally `self.__transfer in self.__submitted_dict`, except `transfer` is not a hashable type.

> My code that previously segfaulted after about 12 hours on average has been running for a few days without problems. I think that that's good evidence that the problem is fixed.

Fantastic !

I pushed it to master and released 1.7.1 with it.

Thank you for the very efficient debugging & bug reporting, and sorry for my slow responses.
