### ISSUE TITLE
Would you consider LGPL licensing?

### ISSUE THREAD

**Issue by projectgus** [vpelletier/python-libusb1#6]
Hi,

Sorry if this is out of line, I just thought I'd ask if you'd be interested in licensing python-libusb1 as LGPL?

I started using your library in a non-GPL-compatible application and I somehow thought until now it was LGPL (I think probably because libusb is LGPL).

I noticed that the only significant contributions so far are yours, so it should be possible to relicense without any other contributor agreements.

My situation is of course entirely my fault for choosing an inappropriate GPL-licensed package. And licensing is entirely your personal choice so I don't mean to put any pressure on you. If you want to keep the current licensing then I'd understand entirely. I just thought I'd ask on the offchance.

Thanks again for all your work on python-libusb1 btw, it's really nice to work with!

Angus

**Comment by vpelletier** [comment]
Hello,

I didn't think much when selecting the license for this project: most of my projects not being libraries, I picked the GPLv2 and mechanically copied it over to each new repository...

As the intent of python-libusb1 is to stick to the libusb API with just the amount of code needed to make it pythonic, using the LGPL seems reasonable to me. Especially, as you point out, as libusb1 is LGPL.

I think I'll switch to the "LGPLv2 or later" variant, following libusb1's licensing.

Also, I'm happy to hear from python-libusb1 users - especially happy ones !
Regards,
Vincent

**Comment by projectgus** [comment]
Thank you Vincent, much appreciated!

Angus

**Comment by vpelletier** [comment]
Re-licensed, PR merged, and released as 1.3.2 . Thanks !
