### ISSUE TITLE
transfer.getStatus() always returns 0 and transfert interrupt is not freed

### ISSUE THREAD

**Issue by amjadtaleb** [vpelletier/python-libusb1#66]
This is a simplified version of a code I am using
```python
def processReceivedData(transfer):
    if transfer.getStatus() != usb1.TRANSFER_COMPLETED:
        print('Exiting transfer callback')
        # transfer.doom()
        return
    actual_sent = transfer.getActualLength()
    data = transfer.getBuffer()

    if actual_sent == len(data): #this is only way to return without submitting
        # transfer.close()
        return
    else:
        ... do something with data...
        transfer.submit()
```

```python
with usb1.USBContext() as context:
    handle = context.openByVendorIDAndProductID()
    with handle.claimInterface(0):
        transfer = handle.getTransfer(0)  # libusb_alloc_transfer
        transfer = handle.getTransfer(0) 
        transfer.setInterrupt(endpoint=INT_IN_EP, buffer_or_len=3072, callback=processReceivedData, user_data=None, timeout=0)
        transfer.submit()
        handle.bulkWrite(endpoint=BULK_OUT_EP, data=buff, timeout=0) # configure device
        handle.bulkWrite(endpoint=BULK_OUT_EP, data=buff, timeout=0) # trigger raeding
        while transfer.isSubmitted():
            try:
                context.handleEvents()
            except usb1.USBErrorInterrupted as e:
                pass
        handle.bulkWrite(endpoint=BULK_OUT_EP, data=buff, timeout=0) # stop reading
```

The problem two parts:
1. transfer.getStatus() is always returning 0, this does not happen in the C code I have for this device.
2. I found a way to force the callback function to return, however, the interrupt is not being set free.

I tried to close or doom the transfer but all methods are raising errors. The original code I use in C to free the interrupt is:
```C
  libusb_free_transfer(transfer);
  transfer_pointer = NULL;
```

**Comment by vpelletier** [comment]
Hello,

About your first point, are you sure the transfer did in fact fail, despite what python-libusb1 is reporting as status ? If you are running on Linux you could check usbmon to see the URB submission and completion events, for example, to see what the kernel is seeing.

About your second point, what is the error reported by `close` ? This method is where `libusb_free_transfer` is called. `doom` itself is only setting a pure python property to a boolean value without even calling into libusb, so I do not see how this would raise anything. What it does though is to cause `close` to be called upon the next transfer completion. How did you identify that some transfer(s) does not get freed ?

About the example code:

> ```python
>     if actual_sent == len(data): #this is only way to return without submitting
> ```

The callback function passed to an `USBTransfer` will not resubmit the transfer on return, so to me this comment does not make sense to me. There is a special class, `USBTransferHelper`, which precisely does resubmit transfers based on the value returned by their completion method, but the bare `USBTransfer` completion handler does no such thing.

> ```python
>        transfer = handle.getTransfer(0)  # libusb_alloc_transfer
>        transfer = handle.getTransfer(0) 
> ```

I am not sure why the double-instanciation here: is it to illustrate a memory leak ? The destructor of the first instance should be called upon the next garbage collector trigger, which in turn will close this transfer and hence call `libusb_free_transfer`. I would expect this to happen before the process exits if anything gets transferred.

**Comment by amjadtaleb** [comment]
Hi, and thank you for the quick reply.
You are completely right, the interrupt should not fail, this was the problem confusing me. Thanks for advice.

I managed to make the device work without problems by checking the value of a global variable that gets updated inside the callback function, and breaking the ```while transfer.isSubmitted():``` loop.

The issue is solved which was really just my bad code.
