### ISSUE TITLE
Event handler context

### ISSUE THREAD

**Issue by ValaJeyhani** [vpelletier/python-libusb1#89]
Thanks for the great library. The asynchronous support is vital for our application and your library handles it beautifully! 

I have a question though. In what context are the event handler callbacks called? Is it a different thread? Should I be worried about issues related to concurrent execution?

Cheers,
Vala

**Comment by ValaJeyhani** [comment]
I guess the answer is any context that the `handleEvents*` functions are called in. Is that correct? Am I right that calling the `handleEvents*` is necessary to process events?

**Comment by vpelletier** [comment]
Thanks for the kind words.

> I guess the answer is any context that the handleEvents* functions are called in. Is that correct? Am I right that calling the handleEvents* is necessary to process events?

Correct and correct. I try to follow `libusb1`'s design principles, and one of those is to not create threads behind the back of the application.

For completeness, there is nowadays one exception on `libusb1`'s side about hotplug even handling, where [the library's internal state is updated using a thread](https://libusb.sourceforge.io/api-1.0/group__libusb__hotplug.html#ga5ab3955e2110a3099497a66256fb7fab) - but this should not call into any application code, not even callbacks - so this should be invisible to the python interpreter.

**Comment by ValaJeyhani** [comment]
Thanks @vpelletier for the clarification!
